<a href="https://colab.research.google.com/github/ramkamal2000/cs6910_assignment3/blob/main/challenge.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Mouting Drive

In [2]:
'''
from google.colab import drive
drive.mount('/content/drive')
'''

Mounted at /content/drive


# Importing Required Libraries

In [194]:
import pandas as pd
import numpy as np
import html
import random
import os
from IPython.core.display import display, HTML
from IPython.display import clear_output
from time import sleep

from PIL import Image, ImageDraw

# Loading Dataset

In [58]:
# CHANGE ACCORDINGLY

root_dir = '/content/drive/MyDrive/Colab Notebooks/DL3'
# root_dir = os.getcwd()

In [59]:
# loading attention predictions
path_attn_greedy = root_dir+'/attention/attn_greedy.csv'

df_attn_greedy = pd.read_csv(path_attn_greedy)

X = df_attn_greedy.X.to_list()
Y_true = df_attn_greedy.Y_pred.to_list()
Y_pred = df_attn_greedy.Y_true.to_list()
match = [1*(a==b) for a,b in zip(Y_true, Y_pred)]

In [60]:
# loading attention weights
path_attn_weights = root_dir+'/attention/attn_weights'
all_attn_weights = pd.read_pickle(path_attn_weights)

# Function To Help Visualize Attention

In [181]:
# function to help visualize which input characters are being focussed on at each time step
def visualize_attention(input_word, output_word, attn_weights):
  
  input_len = len(input_word)
  output_len = len(output_word)

  attn_weights = attn_weights / attn_weights.sum(axis=1, keepdims=True)

  for i, weights in enumerate(attn_weights):
    
    max_alpha = 0.8 
    highlighted_input_text = []
    
    for j in range(input_len):
      weight = weights[j]
      highlighted_input_text.append('<span style="background-color:rgba(206,135,250,' + str(weight / max_alpha) + ');">' + html.escape(input_word[j]) + '</span>')
    
    highlighted_input_split = ' '.join(highlighted_input_text)+'<br/>'
    highlighted_input = ''.join(highlighted_input_text)+'<br/>'
    
    print('Output:')
    print(output_word[:i+1])

    print('Input:')
    display(HTML(highlighted_input))

    sleep(1)
    clear_output(wait=True)

  clear_output()

# Test Example

In [188]:
# CHANGE ACCORDINGLY

x = 10

In [191]:
input_word = X[x]
output_word = Y_pred[x]

attn_weights = all_attn_weights[x][:-1]
attn_weights = np.vstack([wt[0][0] for wt in attn_weights])
attn_weights = attn_weights[:, :len(input_word)]

input_word, output_word

('oththulaikka', 'ஒத்துழைக்க')

In [192]:
visualize_attention(input_word, output_word, attn_weights)

# Toy Example

In [185]:
input_word = 'cart'
output_word = 'காலயய'

In [186]:
# must be output_len X input_len
attn_weights = np.array([[10., 2, 4, 1],
                         [3, 10, 6, 0],
                         [1, 1, 10, 3],
                         [4, 5, 6, 5],
                         [10, 0, 0, 0]])
print(attn_weights)

[[10.  2.  4.  1.]
 [ 3. 10.  6.  0.]
 [ 1.  1. 10.  3.]
 [ 4.  5.  6.  5.]
 [10.  0.  0.  0.]]


In [187]:
visualize_attention(input_word, output_word, attn_weights)